apiVersion: v1
kind: ConfigMap
metadata:
  name: team-factory
  namespace: factory-stock-dash-dev
data:
  STOCK_SYMBOL: "AKAM"
  STOCK_PROVIDER: "Yahoo Finance"
  REFRESH_INTERVAL_SECONDS: "60"
  PORT: "3000"
